apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ include "helm-chart.fullname" . }}-api
spec:
  ports:
  - port: 8000
    name: high
    protocol: TCP
    targetPort: 8000
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ include "helm-chart.fullname" . }}-front
spec:
  ports:
  - port: 3000
    name: high
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
