apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helm-chart.name" . }}-core-restapi
    tier: restapi
  name: {{ include "helm-chart.fullname" . }}-core-restapi
spec:
  ports:
  - port: 8000
    name: high
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ include "helm-chart.name" . }}-core-restapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helm-chart.name" . }}-webapp
  name: {{ include "helm-chart.fullname" . }}-webapp
spec:
  ports:
  - port: 3000
    name: high
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ include "helm-chart.name" . }}-webapp
    
